Makefile
Source files from new common subdirectory were not added to the source tarball. Thus the compile stage failed
=> Fix package build

common/src/lookup.rs, firecracker-pilot/src/defaults.rs, firecracker-pilot/src/firecracker.rs
The firecracker startup procedure in resume mode needs to setup the control channels prior launching the actual firecracker program to allow synchronisation of guest vs. host data flow. If there is no check that the firecracker binary exists we still perform all the pre setup and waiting calls and the actual error condition is only visible in debug mode. Therefore an early exit condition that checks if there is a firecracker binary found on the host improves the user experience. This Fixes #129
=> Firecracker sanity check

common/src/error.rs, common/src/lookup.rs, firecracker-pilot/src/defaults.rs, firecracker-pilot/src/firecracker.rs, podman-pilot/src/defaults.rs, podman-pilot/src/podman.rs
Added FlakeError for this condition. Related to Issue #9
=> Better error message for fs::read_dir

firecracker-pilot/src/config.rs
Allowed values for cache_type are Writeback and Unsafe
=> Fixed firecracker serde schema

Makefile, common/Cargo.toml, common/src/config.rs, common/src/defaults.rs, common/src/lib.rs, firecracker-pilot/src/app_path.rs, firecracker-pilot/src/config.rs, firecracker-pilot/src/defaults.rs, firecracker-pilot/src/firecracker.rs, flakes.yml, package/flake-pilot.spec, podman-pilot/src/config.rs, podman-pilot/src/podman.rs
Let podman and firecracker pilots read /etc/flakes.yml if present to allow configuration of several general settings. Proper defaults are encoded in case no data is provided
=> Added support for systemwide flake config

firecracker-pilot/guestvm-tools/sci/src/main.rs, firecracker-pilot/src/config.rs, firecracker-pilot/src/main.rs, firecracker-pilot/src/tests.rs, podman-pilot/src/config.rs
A matter of taste, but I value test code to be separated from the actual implementation code
=> Don't mix tests with implementation

common/src/command.rs, podman-pilot/Cargo.toml, podman-pilot/src/podman.rs
In case a resume type flake has lost its cid metadata which can
happen on e.g powerfail, the resume of the instance should cleanup
the left over container instance and start from scratch.
This Fixes #23
=> Force cleanup of resume type flakes

Makefile, completion/flake-ctl, package/flake-pilot.spec
Add completion for flake-ctl. This Fixes #18
=> Add bash completion

.github/workflows/ci-compile.yml, firecracker-pilot/guestvm-tools/sci/Cargo.toml, firecracker-pilot/guestvm-tools/sci/src/main.rs, package/flake-pilot.spec
Replace external socat call in sci with rust implementation based on the pty, libc and vsock crates.
This Fixes #8
=> Prevent use of socat in sci

Cargo.toml
Edition 2021 is used in several src setup which implies workspace resolver version 2. Make this a permanent setting and don't let it assume an implicit resolver version
=> Fix workspace resolver

firecracker-pilot/guestvm-tools/sci/src/defaults.rs, firecracker-pilot/guestvm-tools/sci/src/main.rs, firecracker-pilot/src/main.rs, flake-ctl/src/firecracker.rs
Reboot, terminal allocation and pivot of a firecracker machine requires access to sysrq, pts devices and more. sci mounts all kernel filesystems but this requires the mountpoints /proc, /sys /dev, /dev/pts to be available. Some prebuild firecracker images comes without these mountpoints (non FHS compliant btw). With this commit we make sure that at registration time the image has this mountpoint such that the sci issued system mounts can succeed.
=> Make sure system mount point exists for sci

firecracker-pilot/guestvm-tools/sci/src/main.rs
In resume mode the firecracker pilot uses a vsock connection for the host <-> guest data transfer. On the guest the command is by default called in a new PTY. However if this is not possible e.g because the guest does not support pty allocation there should be a fallback allocating the standard channels directly.
=> Use raw channel fallback if pty setup failed

flake-ctl/src/firecracker.rs
When using an overlay sci mounts the new root to /mnt prior pivot. Thus make sure /mnt exists as mountpoint directory in the image at import time
=> Make sure /mnt mountpoint exists for firecracker

README.md, doc/flake-ctl-firecracker-register.rst, firecracker-pilot/guestvm-tools/sci/src/main.rs, firecracker-pilot/src/config.rs, firecracker-pilot/src/firecracker.rs, flake-ctl/src/app.rs, flake-ctl/src/app_config.rs, flake-ctl/src/cli.rs, flake-ctl/src/main.rs, flake-ctl/template/firecracker-flake.yaml
The vsock communication between guest and host was established with the firecracker pilot only for resume type registrations. For those it's required because you cannot mux one serial terminal between parallel applications running at the same time in the guest. So in resume mode each call has its own socket and channels. However, there is no reason to not also support that type of data flow between guest and host for one time calls which fires up the VM, starts the application and shuts down the VM. This commit adds support for forcing the vsock communication also for the simple app registration. The default stays on serial though.
=> Add support for force vsock on firecracker pilot

common/src/command.rs, common/src/error.rs, firecracker-pilot/src/config.rs, firecracker-pilot/src/firecracker.rs, flake-ctl/src/app.rs, flake-ctl/src/app_config.rs, flake-ctl/src/main.rs, flake-ctl/src/podman.rs, podman-pilot/src/config.rs, podman-pilot/src/podman.rs
Make sure the real command that is called through sudo is  displayed. Also fix that the runas information is really used
=> Fix error handling

firecracker-pilot/Cargo.toml, firecracker-pilot/guestvm-tools/sci/src/defaults.rs, firecracker-pilot/guestvm-tools/sci/src/main.rs, firecracker-pilot/src/defaults.rs, firecracker-pilot/src/firecracker.rs, package/flake-pilot.spec
Do not shell out socat and use proper UnixListener/UnixStream to do this job. This version of the commit works but I stumbled across a few issues:
1. Permission denied when the UnixListener runs as user and the firecracker process was called as root (run_as: root in the flake). The former implementation ran socat via sudo in the same way as the firecracker process. Thus if you register the flake to run as root it can now also only be called as root, which is acceptable.
2. The behavior in interactive sessions differs compared to socat. When sci in the guest is called it creates a pty and all data is copied to the vsock stream. The host connects via an UDS socket to this data and we multiplex stdin->stream and stream->stdout. When doing this with socat the behavior is different in a way …
=> Prevent use of socat in firecracker-pilot

firecracker-pilot/guestvm-tools/sci/src/main.rs, flake-ctl/Cargo.toml, flake-ctl/src/app.rs
The system wide configuration file was not read by flake-ctl only by the pilots. This commit fixes it
=> Make sure flake-ctl also reads /etc/flakes.yml

doc/flake-ctl-podman-load.rst, flake-ctl/src/cli.rs, flake-ctl/src/podman.rs
At present in order to load a container the full file name must be specified. In an automated setup where the container is delivered by a source such as an RPM package and then loaded by another process the exact filename may not be known. We expect that the user provide the path to the tarball including the beginning of the archive name. If multiple archives match the highest file based on alpha-numeric sorting is used to load as a container.
=> Handle incomplete container path

doc/flake-ctl-podman-register.rst
Using the term "container name" can be confusing and interpreted as simply the name of the container itself. What we really need to make registration work is the path of the container in the local registry. Clarify the documentation by adding a not ethat points out this potential pitfall.
=> Doc clarification

common/src/container.rs, common/src/defaults.rs
podman differentiates the runroot between root and rootless calls. If you initially call a flake as a user the initial podman database gets setup as rootless variant which also allows root based workloads without permission issues. However, if you do it the other way round the runroot is setup for root only which prevents the flake to be called as normal user. To handle this permission issues we have fix methods in the flake common code to change the permissions according to the calling user via sudo. The code to handle permissions for the runroot target has to apply for all users as we can't predict if the storage will be setup initially as rootless or for root only
=> Fixed the runroot permission fixup

podman-pilot/src/podman.rs
For provisioning of host dependencies copy symlinks such that they appear under their name as a file and not as a symlink. We use this logic for the host dependency sync only to be less strict on versioned library syncing
=> Copy symlinks for host dependencies

doc/podman-pilot.rst, podman-pilot/src/podman.rs
When calling the flake and stdout/stderr gets redirected into a pipe like `flake | grep ... | cut ...` the pilot binary runs in a dead lock because there is no reader/writer to feed the pipe from the child process (podman) executed via the pilot. This commit fixes it by making sure all data from the child gets read first and then passed along to stdout/stderr of the caller.
=> Fixed podman call dead lock

doc/podman-pilot.rst, podman-pilot/Cargo.toml, podman-pilot/src/podman.rs
We support the `%interactive` flag to set interactive commands. With this commit I added a terminal detection such that we normally get dropped into the right caller type but still can overwrite the detection via the mentioned option
=> Automatically detect terminal mode

doc/podman-pilot.rst, podman-pilot/src/podman.rs
The podman runtime arguments allows to set environment variable placeholders starting with '%' and followed by the name of the environment variable. For example %HOME will be replaced to the value of $HOME of the calling user.  If the given placeholder cannot be translated into an  existing environment variable it will be turned into the  variable name, $HOME in the above example.
=> Allow env placeholders for the podman pilot

.github/workflows/ci-robot-tests.yml, doc/podman-pilot.rst, firecracker-pilot/guestvm-tools/sci/src/main.rs, podman-pilot/src/podman.rs
**Fix container cleanup**
A flake configured to be attached can also be re-started using the same container storage. However, the container was always removed when the command exited. This commit fixes it to avoid removing the container of attach type flakes. In addition a flake option %remove was added to allow removing the container created for resume and attach  type flakes
**Fix building runtime arguments**
Use get_run_cmdline method everywhere
=> Fix container cleanup

firecracker-pilot/src/config.rs, flake-ctl/src/app_config.rs, podman-pilot/Cargo.toml, podman-pilot/src/config.rs, podman-pilot/src/podman.rs
If a flake which is not a resume or attach flake is called twice with the same invocation arguments an error message is displayed to give this invocation a new name via the `@NAME` runtime option. This commit makes this more comfortable and automatically assigns a random sequence number for the call if no `@NAME` is given.
=> Create sequence number for the same invocation
